namespace NoMansSky.Api
{
    /// <summary>
    /// Manages all Reality mbin files in the API.
    /// </summary>
    public interface IRealityManager
    {
        /// <summary>
        /// Represents a Reality Manager mbin file.
        /// <br/>The exact mbin type is GcRealityManagerData.
        /// <br/><br/>This mbin file is located in METADATA\REALITY
        /// </summary>
        public IRealityManagerFile DefaultReality{ get; }

        /// <summary>
        /// Represents a Journey Reality mbin.
        /// <br/>The exact mbin type is GcJourney.
        /// <br/><br/>This mbin file is located in METADATA\REALITY
        /// </summary>
        public IJourneyFile Journey{ get; }

        /// <summary>
        /// Represents a Wiki Reality mbin.
        /// <br/>The exact mbin type is GcWiki.
        /// <br/><br/>This mbin file is located in METADATA\REALITY
        /// </summary>
        public IWikiFile Wiki{ get; }

        /// <summary>
        /// Represents a Wiki Reality mbin.
        /// <br/>The exact mbin type is GcWiki.
        /// <br/><br/>This mbin file is located in METADATA\REALITY
        /// </summary>
        public IWikiFile Catalogue{ get; }

        /// <summary>
        /// Represents a Base Building Parts Data Table mbin.
        /// <br/>The exact mbin type is GcBaseBuildingPartsDataTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IBaseBuildingPartsDataFile BaseBuildingAutoGeneratedParts{ get; }

        /// <summary>
        /// Represents a Base Building Costs mbin.
        /// <br/>The exact mbin type is GcBaseBuildingCostsTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IBaseBuildingCostsFile BaseBuildingCosts{ get; }

        /// <summary>
        /// Represents a Base Building Parts mbin.
        /// <br/>The exact mbin type is GcBaseBuildingPartsTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IBaseBuildingPartsFile BaseBuildingParts{ get; }

        /// <summary>
        /// Represents a Base Building Table mbin.
        /// <br/>The exact mbin type is GcBaseBuildingTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IBaseBuildingFile BaseBuildingObjects{ get; }

        /// <summary>
        /// Represents a Base Building Table mbin.
        /// <br/>The exact mbin type is GcBaseBuildingTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IBaseBuildingFile BaseBuildingTable{ get; }

        /// <summary>
        /// Represents a Combat Effects Table mbin.
        /// <br/>The exact mbin type is GcCombatEffectsTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public ICombatEffectsFile CombatEffects { get; }

        /// <summary>
        /// Represents a Player Damage Table mbin.
        /// <br/>The exact mbin type is GcPlayerDamageTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IPlayerDamageFile PlayerDamageTable { get; }

        /// <summary>
        /// Represents a Dialog Clearance Table mbin.
        /// <br/>The exact mbin type is GcDialogClearanceTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IDialogClearanceFile DialogClearance { get; }

        /// <summary>
        /// Represents a Cost Table mbin.
        /// <br/>The exact mbin type is GcCostTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public ICostsFile CostTable { get; }

        /// <summary>
        /// Represents a Consumable Item Table mbin.
        /// <br/>The exact mbin type is GcConsumableItemTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IConsumableItemsFile ConsumableItems { get; }

        /// <summary>
        /// Represents a Discovery Reward Lookup Table mbin.
        /// <br/>The exact mbin type is GcDiscoveryRewardLookupTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IDiscoveryRewardsFile DiscoveryRewards { get; }

        /// <summary>
        /// Represents a Expedition Event Table mbin.
        /// <br/>The exact mbin type is GcExpeditionEventTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IExpeditionEventsFile ExpeditionEvents { get; }

        /// <summary>
        /// Represents a Expedition Reward Table mbin.
        /// <br/>The exact mbin type is GcExpeditionRewardTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IExpeditionRewardsFile ExpeditionRewards { get; }

        /// <summary>
        /// Represents a Frigate Flyby Table mbin.
        /// <br/>The exact mbin type is GcFrigateFlybyTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IFrigateFlybyFile FrigateFlybyTable { get; }

        /// <summary>
        /// Represents a Freighter Dungeons Table mbin.
        /// <br/>The exact mbin type is GcFreighterDungeonsTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IFreighterDungeonsFile FreighterDungeons { get; }

        /// <summary>
        /// Represents a Freighter Trait Table mbin.
        /// <br/>The exact mbin type is GcFrigateTraitTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IFreighterTraitFile FreighterTraits { get; }

        /// <summary>
        /// Represents a Generated Base Templates Table mbin.
        /// <br/>The exact mbin type is GcGeneratedBaseTemplatesTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IGeneratedBaseTemplatesFile GeneratedBaseTemplates { get; }

        /// <summary>
        /// Represents a Inventory Table mbin.
        /// <br/>The exact mbin type is GcInventoryTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IInventoriesFile InventoryTable { get; }

        /// <summary>
        /// Represents a Legacy Item Table mbin.
        /// <br/>The exact mbin type is GcLegacyItemTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IBaseBuildingFile LegacyBaseBuildingObjects { get; }

        /// <summary>
        /// Represents a Legacy Item Table mbin.
        /// <br/>The exact mbin type is GcLegacyItemTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public ILegacyItemsFile LegacyItems { get; }

        /// <summary>
        /// Represents a Maintenance Groups Table mbin.
        /// <br/>The exact mbin type is GcMaintenanceGroupsTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IMaintenanceGroupsFile MaintenanceGroups { get; }

        /// <summary>
        /// Represents an Alien Puzzles Table mbin.
        /// <br/>The exact mbin type is GcAlienPuzzleTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IAlienPuzzlesFile AlienPuzzles { get; }

        /// <summary>
        /// Represents the NMS Reality Procedural Technology Table mbin.
        /// <br/>The exact mbin type is GcProceduralTechnologyTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IProceduralTechnologiesFile ProceduralTechnologies_NMS { get; }

        /// <summary>
        /// Represents an Alien Speech Table mbin.
        /// <br/>The exact mbin type is GcAlienSpeechTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IAlienSpeechFile AlienSpeechTable { get; }

        /// <summary>
        /// Represents the NMS Reality Product Table mbin.
        /// <br/>The exact mbin type is GcProductTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IProductsFile Products_NMS{ get; }

        /// <summary>
        /// Represents a Recipe Table mbin.
        /// <br/>The exact mbin type is GcRecipeTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IRecipesFile Recipies { get; }

        /// <summary>
        /// Represents the NMS Reality Substance Table mbin.
        /// <br/>The exact mbin type is GcSubstanceTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public ISubstancesFile Substances_NMS { get; }

        /// <summary>
        /// Represents the NMS Reality Technology Table mbin.
        /// <br/>The exact mbin type is GcTechnologyTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public ITechnologiesFile Technologies_NMS { get; }

        /// <summary>
        /// Represents a Purchaseable Building Blueprints Table mbin.
        /// <br/>The exact mbin type is GcPurchaseableBuildingBlueprints.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IPurchaseableBuildingBluprintsFile PurchaseableBuildingBluprints { get; }

        /// <summary>
        /// Represents a Procedural Technology Table mbin.
        /// <br/>The exact mbin type is GcProceduralTechnologyTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IProceduralTechnologiesFile ProceduralTechnologies { get; }

        /// <summary>
        /// Represents a Procedural Product Table mbin.
        /// <br/>The exact mbin type is GcProceduralProductTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IProceduralProductsFile ProceduralProducts { get; }

        /// <summary>
        /// Represents a Player Weapon Properties Table mbin.
        /// <br/>The exact mbin type is GcPlayerWeaponPropertiesTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IPlayerWeaponPropertiesFile PlayerWeaponProperties { get; }

        /// <summary>
        /// Represents a Purchaseable Specials Table mbin.
        /// <br/>The exact mbin type is GcPurchaseableSpecials.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IPurchaseableSpecialsFile PurchaseableSpecials { get; }

        /// <summary>
        /// Represents a Rewards Table mbin.
        /// <br/>The exact mbin type is GcRewardTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IRewardsFile Rewards { get; }

        /// <summary>
        /// Represents a Settlement Perks Table mbin.
        /// <br/>The exact mbin type is GcSettlementPerksTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public ISettlementPerksFile SettlementPerks { get; }

        /// <summary>
        /// Represents a Tech Box Table mbin.
        /// <br/>The exact mbin type is GcTechBoxTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public ITechBoxFile TechBox { get; }

        /// <summary>
        /// Represents a Trading Class Table mbin.
        /// <br/>The exact mbin type is GcTradingClassTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public ITradingClassFile TradingClass { get; }

        /// <summary>
        /// Represents a Trading Class Table mbin.
        /// <br/>The exact mbin type is GcTradingClassTable.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IItemCostsFile TradingItemCosts { get; }

        /// <summary>
        /// Represents an Unlockable Trees mbin.
        /// <br/>The exact mbin type is GcUnlockableTrees.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IUnlockableItemsFile UnlockableItems { get; }

        /// <summary>
        /// Represents an Unlockable Season Rewards mbin.
        /// <br/>The exact mbin type is GcUnlockableSeasonRewards.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IUnlockableSeasonRewardsFile UnlockableSeasonRewards { get; }

        /// <summary>
        /// Represents an Unlockable Twitch Rewards mbin.
        /// <br/>The exact mbin type is GcUnlockableTwitchRewards.
        /// <br/><br/>This mbin file is located in METADATA\REALITY\TABLES
        /// </summary>
        public IUnlockableTwitchRewards UnlockableTwitchRewards { get; }
    }
}
